package exceptions;

public class ExceptionDemo5 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int number = 30;
		String name = null;
		System.out.println(1);
try {
	System.out.println(name.length());
	System.out.println(number/0);
}catch(ArithmeticException ex) {
	ex.printStackTrace();
}
catch(NullPointerException ex) {
	ex.printStackTrace();
}
System.out.println(3);
	}

}
